#!/bin/sh

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix
#### category networking and dns and dhcp
#### installed_by_default no
#### gateway_only yes
#### description
## prevent resolvconf from modifying <code>/etc/resolv.conf</code>
#### meta end

make_resolv_conf(){
   :
}
